name: deploy-book

on:
  push:
    branches:
      - main

env:
  BASE_URL: /${{ github.event.repository.name }}

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-book:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build Jupyter Book
        run: jupyter-book build .

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_build/html"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
