name: Deploy Preview to Netlify

on:
  push:
    branches:
      - translation
      - develop
      - 'feature/**'
    paths:
      - '**/decorate.bash'
      - '_config.yml'
      - 'locale/**'
      - '.github/workflows/preview-deploy.yml'
      - '**/*.md'
      - '**/*.ipynb'
      - 'requirements.txt'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install sphinx-intl

      - name: Compile translations
        run: |
          echo "Compiling .po files to .mo files..."
          sphinx-intl build

      - name: Build HTML (English)
        run: sphinx-build -b html -D language=en . _build/html/en

      - name: Build HTML (Spanish)
        run: sphinx-build -b html -D language=es . _build/html/es

      - name: Archive built site as artifact
        uses: actions/upload-artifact@v4
        with:
          name: multilingual-preview-raw
          path: _build/

  decorate:
    name: Inject Language Menu
    runs-on: ubuntu-latest
    needs: build-preview
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download raw HTML artifact
        uses: actions/download-artifact@v4
        with:
          name: multilingual-preview-raw
          path: _build/

      - name: Run decorate.bash
        run: bash decorate.bash

      - name: Upload decorated HTML
        uses: actions/upload-artifact@v4
        with:
          name: multilingual-preview-decorated
          path: _build/html/

  deploy-netlify:
    name: Deploy Preview to Netlify
    runs-on: ubuntu-latest
    needs: decorate
    steps:
      - name: Download decorated HTML
        uses: actions/download-artifact@v4
        with:
          name: multilingual-preview-decorated
          path: ./site

      - name: Create root index.html
        run: |
          cat > ./site/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <title>EMG Preview - Multilingual</title>
            <meta http-equiv="refresh" content="0; url=./en/">
            <link rel="canonical" href="./en/">
          </head>
          <body>
            <h1>Redirecting...</h1>
            <p>If you are not redirected automatically, choose your language:</p>
            <ul>
              <li><a href="./en/">English</a></li>
              <li><a href="./es/">Español</a></li>
            </ul>
            <script>
              window.location.href = './en/';
            </script>
          </body>
          </html>
          EOF

      - name: Debug - List files
        run: |
          echo "Files in ./site:"
          find ./site -type f -name "*.html" | head -10
          echo "Directory structure:"
          ls -la ./site/

      - name: Prepare for Netlify deployment
        run: |
          # Disable Jekyll processing
          touch ./site/.nojekyll
          # Add basic redirects file
          echo "/* /index.html 200" > ./site/_redirects

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './site'
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Preview deploy from ${{ github.ref_name }}"
          alias: preview-${{ github.run_number }}
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
